export const getText = () => {
  return {
    text: [
      'Consequatur summas voluptates non modo parvo, sed per me nihilo, si potest; Cum praesertim illa perdiscere ludus esset. Quae iam oratio non a philosopho aliquo, sed a censore opprimenda est. Quid turpius quam sapientis vitam ex insipientium sermone pendere? An potest, inquit ille, quicquam esse suavius quam nihil dolere? Cur, nisi quod turpis oratio est? Quis, quaeso, illum negat et bonum virum et comem et humanum fuisse? Nam et a te perfici istam disputationem volo, nec tua mihi oratio longa videri potest.',
      'Non semper, inquam; An eum locum libenter invisit, ubi Demosthenes et Aeschines inter se decertare soliti sunt? Quid iudicant sensus? Totum genus hoc Zeno et qui ab eo sunt aut non potuerunt aut noluerunt, certe reliquerunt. Negabat igitur ullam esse artem, quae ipsa a se proficisceretur; Te ipsum, dignissimum maioribus tuis, voluptasne induxit, ut adolescentulus eriperes P. Illi enim inter se dissentiunt.',
      'Itaque eos id agere, ut a se dolores, morbos, debilitates repellant. Mihi, inquam, qui te id ipsum rogavi? Sic, et quidem diligentius saepiusque ista loquemur inter nos agemusque communiter. Nondum autem explanatum satis, erat, quid maxime natura vellet. Quod idem cum vestri faciant, non satis magnam tribuunt inventoribus gratiam. Neque solum ea communia, verum etiam paria esse dixerunt. Unum nescio, quo modo possit, si luxuriosus sit, finitas cupiditates habere. Illa argumenta propria videamus, cur omnia sint paria peccata. Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat. Non quaeritur autem quid naturae tuae consentaneum sit, sed quid disciplinae.',
      'Idem iste, inquam, de voluptate quid sentit? Quid enim possumus hoc agere divinius? Cur post Tarentum ad Archytam? Dici enim nihil potest verius. Atque ab his initiis profecti omnium virtutum et originem et progressionem persecuti sunt. Idem etiam dolorem saepe perpetiuntur, ne, si id non faciant, incidant in maiorem. Quod si ita se habeat, non possit beatam praestare vitam sapientia.',
      'Quare, quoniam de primis naturae commodis satis dietum est nunc de maioribus consequentibusque videamus. Tum ille timide vel potius verecunde: Facio, inquit. Quid tanto concursu honestissimorum studiorum, tanto virtutum comitatu, si ea nullam ad aliam rem nisi ad voluptatem conquiruntur? Cum ageremus, inquit, vitae beatum et eundem supremum diem, scribebamus haec. Summum ením bonum exposuit vacuitatem doloris; Igitur ne dolorem quidem. Cur igitur, inquam, res tam dissimiles eodem nomine appellas? Quamquam ab iis philosophiam et omnes ingenuas disciplinas habemus;',
      'Laboro autem non sine causa; Vide ne ista sint Manliana vestra aut maiora etiam, si imperes quod facere non possim. Sic consequentibus vestris sublatis prima tolluntur. An ea, quae per vinitorem antea consequebatur, per se ipsa curabit?',
      'Quae in controversiam veniunt, de iis, si placet, disseramus. Te ipsum, dignissimum maioribus tuis, voluptasne induxit, ut adolescentulus eriperes P. An quod ita callida est, ut optime possit architectari voluptates? Quid ergo attinet gloriose loqui, nisi constanter loquare? Nam quibus rebus efficiuntur voluptates, eae non sunt in potestate sapientis. Ostendit pedes et pectus. Scientiam pollicentur, quam non erat mirum sapientiae cupido patria esse cariorem.',
      'Aliud igitur esse censet gaudere, aliud non dolere. Sed fortuna fortis; Piso igitur hoc modo, vir optimus tuique, ut scis, amantissimus. Non igitur potestis voluptate omnia dirigentes aut tueri aut retinere virtutem. Nunc haec primum fortasse audientis servire debemus. At enim, qua in vita est aliquid mali, ea beata esse non potest. Aut unde est hoc contritum vetustate proverbium: quicum in tenebris? Quid enim est a Chrysippo praetermissum in Stoicis? Scrupulum, inquam, abeunti; Hoc dictum in una re latissime patet, ut in omnibus factis re, non teste moveamur. Haec igitur Epicuri non probo, inquam.',
    ],
  };
};
